# This file was generated by GoReleaser. DO NOT EDIT.
cask "colony-relay" do
  name "colony-relay"
  desc "Message relay for agent-to-agent communication"
  homepage "https://github.com/ff6347/colony-relay"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "colony-relay"

  on_macos do
    on_intel do
      url "https://github.com/ff6347/colony-relay/releases/download/v#{version}/colony-relay_darwin_amd64.tar.gz"
      sha256 "beb5edd8876d3877dfae4a00087fac3ad323021b39a5f1a05244fe86302b4a9d"
    end
    on_arm do
      url "https://github.com/ff6347/colony-relay/releases/download/v#{version}/colony-relay_darwin_arm64.tar.gz"
      sha256 "303f165dff20d1f0a7455fdeba7081fde7fd37e558a2d8999e0fcb737d44f545"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ff6347/colony-relay/releases/download/v#{version}/colony-relay_linux_amd64.tar.gz"
      sha256 "3e12e8ad09c9dd25076ef73078abfe6eba13177f55ca771ebf218e88d08ba06c"
    end
    on_arm do
      url "https://github.com/ff6347/colony-relay/releases/download/v#{version}/colony-relay_linux_arm64.tar.gz"
      sha256 "1bc7efa2f7b5201c6fa8c244379a920de5b1ed4b42802be8527aadc1c354c186"
    end
  end

  # No zap stanza required
end
