# This file was generated by GoReleaser. DO NOT EDIT.
cask "igittigit" do
  name "igittigit"
  desc "CLI for fetching .gitignore templates from GitHub"
  homepage "https://github.com/ff6347/igittigit"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "igittigit"

  on_macos do
    on_intel do
      url "https://github.com/ff6347/igittigit/releases/download/v#{version}/igittigit_darwin_amd64.tar.gz"
      sha256 "ef0b708eac90fa305374c0217117ec7026f3d326ea8dca3665f6e2f8cd6847f4"
    end
    on_arm do
      url "https://github.com/ff6347/igittigit/releases/download/v#{version}/igittigit_darwin_arm64.tar.gz"
      sha256 "e861246147ab0abd03870fa5fc6735c2fc1b6b518ba2291b4b3def9257e06b81"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ff6347/igittigit/releases/download/v#{version}/igittigit_linux_amd64.tar.gz"
      sha256 "3f9280408d6a78be0d0c22a8267164011b228b1e31467056ff23ca831d112c6a"
    end
    on_arm do
      url "https://github.com/ff6347/igittigit/releases/download/v#{version}/igittigit_linux_arm64.tar.gz"
      sha256 "c834d40768d388833281fdb8a544da37cbc83569d89c403e57ae32c2bbd91b43"
    end
  end

  # No zap stanza required
end
