# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Licensor < Formula
  desc "CLI for fetching open source license templates"
  homepage "https://github.com/ff6347/licensor"
  version "1.0.4"
  license "CC-BY-4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ff6347/licensor/releases/download/v1.0.4/licensor_darwin_amd64.tar.gz"
      sha256 "a3afb8576b8b4523551cbf5eb2bd498573ca8b3223f152c1a7f93aed7f057bb9"

      def install
        bin.install "licensor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ff6347/licensor/releases/download/v1.0.4/licensor_darwin_arm64.tar.gz"
      sha256 "d058141cb1656b6daf8463806c9c86611374d08e8866a60f3ccbf12d26bae550"

      def install
        bin.install "licensor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ff6347/licensor/releases/download/v1.0.4/licensor_linux_amd64.tar.gz"
      sha256 "a6198b5bc776d4650d2ebe067e928afe3987f9963322ebfca463ee56bf97af6c"
      def install
        bin.install "licensor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ff6347/licensor/releases/download/v1.0.4/licensor_linux_arm64.tar.gz"
      sha256 "85bf51ab3b8f74eec0309cdbfc2c15172a5d86718df8fc8189c613d42aad583e"
      def install
        bin.install "licensor"
      end
    end
  end
end
