# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Til < Formula
  desc "til (today I learned) CLI"
  homepage "https://github.com/ff6347/til"
  version "1.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ff6347/til/releases/download/v1.2.3/til_darwin_arm64.tar.gz"
      sha256 "edd274cfe62ae8d0f095982751327d8ee7f56720c652e556b362b0c9d0ce27cc"

      def install
        bin.install "til"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ff6347/til/releases/download/v1.2.3/til_darwin_amd64.tar.gz"
      sha256 "c79311c437c7465d6e0216a2d106cf67b38186ea4647812a6815285243cce0c7"

      def install
        bin.install "til"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ff6347/til/releases/download/v1.2.3/til_linux_arm64.tar.gz"
      sha256 "e6ea4cc1a8dd06cd776375928c96e813b0366059cca5ae7aa635938f84eb2b8a"

      def install
        bin.install "til"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ff6347/til/releases/download/v1.2.3/til_linux_amd64.tar.gz"
      sha256 "daf5fd7b94a14a0f7c95a61805c78deeda4050c19052a456111bd210df76e365"

      def install
        bin.install "til"
      end
    end
  end
end
