# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Til < Formula
  desc "til (today I learned) CLI"
  homepage "https://github.com/ff6347/til"
  version "1.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ff6347/til/releases/download/v1.2.4/til_darwin_arm64.tar.gz"
      sha256 "25aaf98e3e17b9622c9bf48a552aaa9e75184cd1d5fa05040f75979fcd040186"

      def install
        bin.install "til"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ff6347/til/releases/download/v1.2.4/til_darwin_amd64.tar.gz"
      sha256 "28902caca8fd1336a3ab8f34808e0652bb50967450133731df0a3ddaeeb9d7b9"

      def install
        bin.install "til"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ff6347/til/releases/download/v1.2.4/til_linux_arm64.tar.gz"
      sha256 "526a2e95d86678ecd4998ecd7f714db105fc6e913c2dfd1bdafb6b5de7a385d3"

      def install
        bin.install "til"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ff6347/til/releases/download/v1.2.4/til_linux_amd64.tar.gz"
      sha256 "dc534080cee16adccd86b5259a92057c7d5f28f1a47d1a6e32204a1b15ef9022"

      def install
        bin.install "til"
      end
    end
  end
end
